#!/bin/bash

echo "Starting Spark cyrpto-currency miner"
MINER=$MINER_EXEC
MINER_URL=$URL
MINER_USERNAME=$USERNAME
MINER_WORKER_ID=$WORKER_ID
MINER_PASSWORD=$PASSWORD

EXEC="$MINER --url=$MINER_URL --userpass=$MINER_USERNAME.$MINER_WORKER_ID:$MINER_PASSWORD"

eval $EXEC